### ISSUE TITLE
[BUG]: "TypeError: Cannot read property 'options' of undefined" when using Service List node

### ISSUE THREAD

**Issue by ChrisRahme** [naimo84/node-red-contrib-dockerode#46]
**Describe the bug**
I am just using an Service List node with no service mentioned, as it should be the case, since I want to list the available services:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/28784897/210507402-ec70ea44-90be-4d24-b596-52880ec4fc7f.png">

I did the exact same for the Container List node, which works fine:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/28784897/210507583-f74d6579-3551-4b18-bd47-dd2ebd1037b8.png">

Even when entering the name or ID of a service just to test the result, I get the same error.

Here is the full traceback:
```
TypeError: Cannot read property 'options' of undefined
    at DockerServiceAction._inputCallback (/data/node_modules/node-red-contrib-dockerode/dist/docker-service-actions.js:19:67)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at DockerServiceAction.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at DockerServiceAction.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
    at DockerServiceAction.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:485:10)
    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
    at processImmediate (internal/timers.js:464:21)
```

**To Reproduce**
1. Configure the module
2. Add a Service List node
3. Start the node with an Input node

<img width="946" alt="image" src="https://user-images.githubusercontent.com/28784897/210508239-24284598-8013-4ea3-bfe7-851cab351a73.png">

**Expected behavior**
This should list the services.

**Additional context**
I just want to list all containers, check if one is unhealthy, and restart its service if so.

**Comment by naimo84** [comment]
Hey @ChrisRahme ,

should be fixed with https://github.com/naimo84/node-red-contrib-dockerode/releases/tag/v0.13.1 😉 

Greets,
Benjamin

**Comment by ChrisRahme** [comment]
Thanks for fixing it, @naimo84  :)

Quick question: Is it not possible to list all containers under a service (including those on another computer)?
